apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-{{ .Values.namespace }}-server
subjects:
  - kind: ServiceAccount
    name: prometheus-server-{{ .Values.namespace }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: prometheus-server
  apiGroup: rbac.authorization.k8s.io
